//POSITION
export const SET_USER_ADDRESS_LIST = 'SET_USER_ADDRESS_LIST';
export const SET_NEAR_PLACES = 'SET_NEAR_PLACES';
export const SET_POS = 'SET_POS';
export const SET_SELECT_ADDR_ITEM = 'SET_SELECT_ADDR_ITEM';
export const SET_SERVICE_REGION = 'SET_SERVICE_REGION';
export const SET_AUTO_REGION = 'SET_AUTO_REGION';
export const PUSH_HISTORY = 'PUSH_HISTORY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
export const REMOVE_HISTORY = 'REMOVE_HISTORY';
export const OPEN_MORE_ADDR_POP = 'OPEN_MORE_ADDR_POP';
export const CLOSE_MORE_ADDR_POP = 'CLOSE_MORE_ADDR_POP';
export const SET_POSITION_STATUS = 'SET_POSITION_STATUS';
export const SET_ORDER_ADDR = 'SET_ORDER_ADDR';


//PRODUCTION
export const SET_CREATE_ORDER = 'SET_CREATE_ORDER';
//COMMON
export const SET_TAB = 'SET_TAB';